sudo: required
language: generic

services:
    - docker
before_install:
    - docker build -t pbryant/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true pbryant/react-test npm run test
after_success:
  - docker build -t pbryant/multi-docker-client ./client
  - docker build -t pbryant/multi-docker-nginx ./nginx
  - docker build -t pbryant/multi-docker-api ./api
  - docker build -t pbryant/multi-docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub creating new repos
  - docker push pbryant/multi-docker-client
  - docker push pbryant/multi-docker-nginx
  - docker push pbryant/multi-docker-api
  - docker push pbryant/multi-docker-worker
